#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# Garm — one-command LIVE SERVER setup (Ubuntu 22.04 / 24.04)
#
# Run this ON A FRESH CLOUD SERVER (as root, or with sudo). It:
#   1. installs Docker,
#   2. clones BOTH Garm repos side by side,
#   3. generates secrets,
#   4. starts everything — MongoDB, both backends, both apps.
#
# Copy-paste to run it (one line):
#   curl -fsSL https://raw.githubusercontent.com/hscreators-dev/garm-admin-portal/main/server-deploy.sh | bash
#
# After it finishes, your site is live at:
#   Customer app :  http://<server-ip>:8080
#   Admin portal :  http://<server-ip>:8081/garm-admin-portal/
#
# ⚠️  It starts in PREVIEW mode (login codes show on screen) so you can test
#     immediately. Before real customers: set NODE_ENV=production and an OTP
#     gateway in /opt/garm/garm-admin-portal/.env — see SERVER_DEPLOY.md.
# ─────────────────────────────────────────────────────────────────────────────
set -e

ADMIN_REPO="https://github.com/hscreators-dev/garm-admin-portal.git"
FAB_REPO="https://github.com/hscreators-dev/Haneef.git"
ROOT="/opt/garm"

echo "▶ Installing Docker (if needed)…"
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi
if ! docker compose version >/dev/null 2>&1; then
  apt-get update -y && apt-get install -y docker-compose-plugin || true
fi

echo "▶ Fetching the code…"
mkdir -p "$ROOT" && cd "$ROOT"
if [ -d "garm-admin-portal/.git" ]; then (cd garm-admin-portal && git pull --ff-only || true); else git clone "$ADMIN_REPO" garm-admin-portal; fi
# The compose expects the customer app in a sibling folder named exactly
# "Latest version of FAB", so clone the Haneef repo into that name.
if [ -d "Latest version of FAB/.git" ]; then (cd "Latest version of FAB" && git pull --ff-only || true); else git clone "$FAB_REPO" "Latest version of FAB"; fi

cd "$ROOT/garm-admin-portal"

echo "▶ Preparing config…"
IP="$(curl -s ifconfig.me || echo YOUR_SERVER_IP)"
if [ ! -f .env ]; then
  cat > .env <<EOF
# Auto-generated by server-deploy. Keep private. Do NOT commit.
# PREVIEW mode: login codes appear on screen so you can test right away.
# BEFORE REAL CUSTOMERS → change NODE_ENV to production and set an OTP gateway
# (see SERVER_DEPLOY.md, "Open it to real customers").
NODE_ENV=development
CUSTOMER_APP_URL=http://$IP:8080
ADMIN_APP_URL=http://$IP:8081
JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')
GARM_SECRET_KEY=$(openssl rand -hex 32)
SMS_PROVIDER=console
PAYMENTS_REQUIRE_GATEWAY=false
EOF
  echo "  ✅ .env created."
else
  echo "  ✅ using existing .env."
fi

echo "▶ Building & starting (first time takes a few minutes)…"
docker compose up -d --build

echo ""
echo "─────────────────────────────────────────────"
echo "  ✅ Garm is LIVE:"
echo "     Customer app :  http://$IP:8080"
echo "     Admin portal :  http://$IP:8081/garm-admin-portal/"
echo ""
echo "  Log in with haneef@garm.com (admin) — the code shows on screen."
echo "  To update after pushing new code:  cd $ROOT/garm-admin-portal && git pull && docker compose up -d --build"
echo "─────────────────────────────────────────────"
