@echo off
REM ============================================================================
REM  Garm - one-click local launcher (Windows)
REM  Double-click this file. It starts EVERYTHING - MongoDB, both backends,
REM  both apps - on your computer. You don't set up MongoDB; it's automatic.
REM  Requirement: Docker Desktop installed and running ->
REM               https://www.docker.com/products/docker-desktop/
REM ============================================================================
cd /d "%~dp0"
echo.
echo   Starting Garm (local)...
echo.

REM 1) Docker check
docker info >nul 2>&1
if errorlevel 1 (
  echo   [!] Docker isn't running or isn't installed.
  echo       Install Docker Desktop (free), open it, then run this again:
  echo       https://www.docker.com/products/docker-desktop/
  echo.
  pause
  exit /b 1
)
echo   [ok] Docker is ready.

REM 2) Create .env with generated secrets on first run
if not exist ".env" (
  echo   [*] First run - generating secrets and a local config...
  for /f "delims=" %%a in ('powershell -NoProfile -Command "[Convert]::ToBase64String((1..48 ^| ForEach-Object {Get-Random -Max 256}))"') do set "JWT=%%a"
  for /f "delims=" %%a in ('powershell -NoProfile -Command "-join ((1..32 ^| ForEach-Object {'{0:x2}' -f (Get-Random -Max 256)}))"') do set "KEY=%%a"
  (
    echo # Auto-generated by start-garm. Safe to keep. Do not share.
    echo NODE_ENV=development
    echo CUSTOMER_APP_URL=http://localhost:8080
    echo ADMIN_APP_URL=http://localhost:8081
    echo JWT_SECRET=%JWT%
    echo GARM_SECRET_KEY=%KEY%
    echo SMS_PROVIDER=console
    echo PAYMENTS_REQUIRE_GATEWAY=false
  ) > .env
  echo   [ok] Config created (.env).
) else (
  echo   [ok] Using existing .env.
)

REM 3) Build & start
echo.
echo   Building and starting everything (first time takes a few minutes)...
docker compose up -d --build

echo.
echo   ============================================================
echo    Garm is running - with its own database!
echo    Customer app :  http://localhost:8080
echo    Admin portal :  http://localhost:8081/garm-admin-portal/
echo    Login: enter a phone/email, the code shows on screen.
echo   ============================================================
echo   To stop later:  docker compose down
echo.
pause
